trigger:
- main  # Adjust based on your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: 'latest'

- script: |
    docker-compose -f docker-compose.yml build
  displayName: 'Build Docker Images'

- script: |
    docker-compose -f docker-compose.yml up -d
  displayName: 'Run Docker Containers'

- script: |
    docker-compose ps
  displayName: 'List Running Containers'

- script: |
    docker-compose down
  displayName: 'Stop and Remove Containers'