trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DB_PASSWORD: '$(dbPassword)'

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        steps:
        - checkout: self
          
        - task: Docker@2
          displayName: 'Build web image'
          inputs:
            command: build
            dockerfile: './movie-search-vue3/Dockerfile'
            repository: '$(dockerRegistry)/movie-search-web'
            tags: |
              $(Build.BuildId)
              latest
              
        - task: Docker@2
          displayName: 'Build API image'
          inputs:
            command: build
            dockerfile: './MovieSearchLogs/Dockerfile'
            repository: '$(dockerRegistry)/movie-search-api'
            tags: |
              $(Build.BuildId)
              latest