version: '3.8'

services:
  web:
    build: ./movie-search-vue3
    environment:
      VITE_DB_GET_API: http://localhost/api/logs/GetLogs
      VITE_DB_POST_API: http://localhost/api/logs/AddLog
    ports:
      - "5173:5173" # Access through Nginx instead

  api:
    build: ./MovieSearchLogs
    environment:
      ConnectionStrings__DbCon: Server=db;Database=MovieSearchLogs;User Id=sa;Password=${DB_PASSWORD};
    expose:
      - "8080:80"

  db:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
    ports:
      - "80:80"
    depends_on:
      - web
      - api
